# Generated by Django 5.2.4 on 2025-08-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
    ]
