# Generated by Django 5.2.4 on 2025-08-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.IntegerField(default=0)),
                ('prompt', models.TextField()),
                ('bot_message', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('chat_type', models.CharField(max_length=255)),
                ('llm', models.CharField(max_length=255)),
            ],
        ),
    ]
