# Generated by Django 5.2.4 on 2025-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_db_name', models.CharField(max_length=255)),
                ('files', models.JSONField(default=list)),
                ('embedding', models.CharField(max_length=64)),
            ],
        ),
    ]
